# Generated by Django 5.2.4 on 2025-07-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armazenamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livre', models.BooleanField(default=True)),
                ('rua', models.CharField(max_length=50)),
                ('predio', models.CharField(max_length=50)),
                ('nivel', models.CharField(max_length=50)),
                ('ap', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('validade', models.DateField()),
                ('data_fabricacao', models.DateField()),
                ('peso', models.CharField(max_length=50)),
                ('lote', models.CharField(max_length=50)),
                ('quantidade', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
