# Generated by Django 5.2.4 on 2025-07-17 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Armazenamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rua", models.CharField(max_length=50)),
                ("predio", models.CharField(max_length=50)),
                ("nivel", models.CharField(max_length=10)),
                ("ap", models.CharField(max_length=10)),
                ("livre", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("peso", models.CharField(max_length=50)),
                ("validade", models.DateField(blank=True, null=True)),
                ("validade2", models.DateField(blank=True, null=True)),
                ("validade3", models.DateField(blank=True, null=True)),
                ("quantidade", models.PositiveIntegerField(default=1)),
                ("data_fabricacao", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Estoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_armazenado", models.DateField()),
                (
                    "local",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produtos.armazenamento",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produtos.produto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("validade", models.DateField()),
                ("quantidade", models.PositiveIntegerField(default=1)),
                ("data_fabricacao", models.DateField(blank=True, null=True)),
                ("numero_lote", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lotes",
                        to="produtos.produto",
                    ),
                ),
            ],
            options={
                "unique_together": {("produto", "validade", "numero_lote")},
            },
        ),
    ]
