# Generated by Sistema de Endereçamento Melhorado
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),  # Ajuste conforme sua última migração
    ]

    operations = [
        migrations.AddField(
            model_name='armazenamento',
            name='codigo',
            field=models.CharField(max_length=20, unique=True, blank=True, null=True, verbose_name='Código do Endereço'),
        ),
        migrations.AddField(
            model_name='armazenamento',
            name='descricao',
            field=models.CharField(max_length=200, blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='armazenamento',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='armazenamento',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação'),
        ),
        migrations.AddField(
            model_name='armazenamento',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última Modificação'),
        ),
    ]
