# Generated by Django 5.2.4 on 2025-07-24 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="quantidade",
        ),
    ]
