# Generated by Copilot on 2025-07-18
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_estoque'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidadeEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validade', models.DateField()),
                ('estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validades', to='produtos.estoque')),
            ],
        ),
    ]
