# Generated by Django 5.2.4 on 2025-07-24 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0002_remove_produto_quantidade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="data_fabricacao",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="validade",
        ),
    ]
