# Generated by Django 5.2.4 on 2025-07-24 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0003_remove_produto_data_fabricacao_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="validade2",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="validade3",
        ),
    ]
