# Generated by Django 5.2.4 on 2025-07-24 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0004_remove_produto_validade2_remove_produto_validade3"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="armazenamento",
            options={"ordering": ["predio", "rua", "nivel", "ap"]},
        ),
        migrations.AlterModelOptions(
            name="estoque",
            options={"ordering": ["-data_armazenado"]},
        ),
        migrations.AlterModelOptions(
            name="lote",
            options={"ordering": ["validade"]},
        ),
        migrations.AddField(
            model_name="armazenamento",
            name="capacidade_maxima",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="armazenamento",
            name="observacoes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="estoque",
            name="observacoes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="estoque",
            name="usuario_responsavel",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="lote",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="produto",
            name="categoria",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="produto",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="produto",
            name="fornecedor",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="produto",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name="Alerta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("vencimento", "Produto Próximo ao Vencimento"),
                            ("vencido", "Produto Vencido"),
                            ("estoque_baixo", "Estoque Baixo"),
                            ("local_lotado", "Local de Armazenamento Lotado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("mensagem", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("lido", "Lido"),
                            ("resolvido", "Resolvido"),
                        ],
                        default="ativo",
                        max_length=10,
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_leitura", models.DateTimeField(blank=True, null=True)),
                (
                    "local",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produtos.armazenamento",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produtos.produto",
                    ),
                ),
            ],
            options={
                "ordering": ["-data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="HistoricoMovimentacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_operacao",
                    models.CharField(
                        choices=[
                            ("entrada", "Entrada"),
                            ("saida", "Saída"),
                            ("transferencia", "Transferência"),
                            ("ajuste", "Ajuste de Estoque"),
                            ("vencimento", "Remoção por Vencimento"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(default=1)),
                ("data_operacao", models.DateTimeField(auto_now_add=True)),
                ("usuario", models.CharField(blank=True, max_length=100, null=True)),
                ("observacoes", models.TextField(blank=True, null=True)),
                (
                    "local_destino",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimentacoes_destino",
                        to="produtos.armazenamento",
                    ),
                ),
                (
                    "local_origem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimentacoes_origem",
                        to="produtos.armazenamento",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produtos.produto",
                    ),
                ),
            ],
            options={
                "ordering": ["-data_operacao"],
            },
        ),
    ]
