# Generated by Django 5.2.4 on 2025-07-24 23:14

import produtos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0005_alter_armazenamento_options_alter_estoque_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="nome",
            field=models.CharField(
                max_length=100, validators=[produtos.models.validar_nome_produto]
            ),
        ),
    ]
