# Generated by Django 5.2.4 on 2025-07-25 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0005_add_categoria_armazenamento"),
        ("produtos", "0006_alter_produto_nome"),
    ]

    operations = []
