# Generated by Django 5.2.4 on 2025-07-26 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_enderecamento_melhorado'),
        ('produtos', '0007_merge_20250725_1456'),
    ]

    operations = [
    ]
