# Generated by Django 5.2.4 on 2025-07-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_merge_20250726_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='armazenamento',
            options={'ordering': ['rua', 'predio', 'nivel', 'ap'], 'verbose_name': 'Endereço de Armazenamento', 'verbose_name_plural': 'Endereços de Armazenamento'},
        ),
        migrations.AlterField(
            model_name='armazenamento',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Se o endereço está ativo para uso', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='armazenamento',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código único no formato RUA-PRÉDIO-NÍVEL-AP', max_length=20, null=True, unique=True, verbose_name='Código do Endereço'),
        ),
        migrations.AlterField(
            model_name='armazenamento',
            name='descricao',
            field=models.CharField(blank=True, help_text='Descrição adicional do endereço', max_length=200, null=True, verbose_name='Descrição'),
        ),
    ]
