# Generated by Django 5.2.4 on 2025-07-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_adicionar_data_alteracao_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='data_alteracao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
