# Generated by Django 5.2.4 on 2025-07-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_alter_historicomovimentacao_tipo_operacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='data_validade',
            field=models.DateField(blank=True, null=True),
        ),
    ]
